// FILE: src/components/dashboard/DashboardPageClient.tsx
/*
 * [ROLE: FRONTEND ENGINEER]
 * Decision: The dashboard composes independent TanStack Query reads so failed
 * widgets can show errors without blocking the whole page shell.
 */
"use client";

import { useMemo } from "react";
import { useQuery } from "@tanstack/react-query";
import { Bot, CheckCircle2, MessageSquareText, PlugZap } from "lucide-react";

import { RecentMessages } from "@/components/dashboard/RecentMessages";
import { StatsCard } from "@/components/dashboard/StatsCard";
import { UsageBar } from "@/components/dashboard/UsageBar";
import { MockMessageSender } from "@/components/messages/MockMessageSender";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { useMessages } from "@/hooks/useMessages";
import { useSettings } from "@/hooks/useSettings";
import { useSubscription } from "@/hooks/useSubscription";
import { apiData } from "@/lib/api/client";

type SafeConnection = {
  id: string;
  phoneNumberId: string;
  displayName: string | null;
  isActive: boolean;
  isVerified: boolean;
};

type ConnectionsResponse = {
  connections: SafeConnection[];
};

type DashboardPageClientProps = {
  mockMode: boolean;
};

function isCurrentMonth(dateValue: string) {
  const date = new Date(dateValue);
  const now = new Date();

  return date.getMonth() === now.getMonth() && date.getFullYear() === now.getFullYear();
}

export function DashboardPageClient({ mockMode }: DashboardPageClientProps) {
  const settingsResult = useSettings();
  const subscription = useSubscription();
  const messagesResult = useMessages({ page: 1, limit: 100 });
  const connectionsQuery = useQuery({
    queryKey: ["whatsapp-connections"],
    queryFn: () => apiData<ConnectionsResponse>("/api/whatsapp/connect"),
  });

  const messages = messagesResult.messages;
  const monthMessages = useMemo(() => messages.filter((message) => isCurrentMonth(message.createdAt)), [messages]);
  const repliedMessages = monthMessages.filter((message) => message.status === "REPLIED");
  const failedMessages = monthMessages.filter((message) => message.status === "FAILED");
  const successRate = repliedMessages.length + failedMessages.length === 0
    ? 0
    : Math.round((repliedMessages.length / (repliedMessages.length + failedMessages.length)) * 100);
  const activeConnection = connectionsQuery.data?.connections.find((connection) => connection.isActive) ?? null;
  const hasError = settingsResult.error || messagesResult.error || connectionsQuery.isError;

  if (settingsResult.isLoading || messagesResult.isLoading || connectionsQuery.isLoading) {
    return (
      <div className="space-y-6">
        <div className="grid gap-4 md:grid-cols-3">
          {Array.from({ length: 3 }, (_, index) => (
            <Skeleton key={index} className="h-32 w-full" />
          ))}
        </div>
        <Skeleton className="h-64 w-full" />
      </div>
    );
  }

  if (hasError) {
    return (
      <Alert>
        <AlertTitle>Dashboard unavailable</AlertTitle>
        <AlertDescription>One or more dashboard requests failed. Refresh the page after checking your session.</AlertDescription>
      </Alert>
    );
  }

  return (
    <div className="space-y-6">
      <div className="grid gap-4 md:grid-cols-3">
        <StatsCard title="Total messages this month" value={String(monthMessages.length)} description="Inbound and outbound records" icon={MessageSquareText} />
        <StatsCard title="AI replies sent" value={String(repliedMessages.length)} description="Replies generated by automation" icon={Bot} />
        <StatsCard title="Reply success rate" value={`${successRate}%`} description="Successful AI replies vs failures" icon={CheckCircle2} />
      </div>
      <div className="grid gap-4 lg:grid-cols-[1fr_340px]">
        <div className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Usage</CardTitle>
            </CardHeader>
            <CardContent>
              <UsageBar planTier={subscription.planTier} used={subscription.usage} />
            </CardContent>
          </Card>
          <RecentMessages messages={messages.slice(0, 5)} />
        </div>
        <div className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>WhatsApp Connection</CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-sm text-muted-foreground">Status</span>
                <Badge variant={activeConnection ? "success" : "warning"}>{activeConnection ? "Connected" : "Not connected"}</Badge>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-sm text-muted-foreground">Auto-reply</span>
                <Badge variant={settingsResult.settings?.autoReplyEnabled ? "success" : "secondary"}>
                  {settingsResult.settings?.autoReplyEnabled ? "Enabled" : "Disabled"}
                </Badge>
              </div>
              <div className="flex items-center gap-2 text-sm">
                <PlugZap className="size-4 text-primary" aria-hidden="true" />
                <span>{activeConnection?.displayName ?? activeConnection?.phoneNumberId ?? "Connect a number to start processing messages."}</span>
              </div>
            </CardContent>
          </Card>
          {mockMode ? (
            <MockMessageSender
              phoneNumberId={activeConnection?.phoneNumberId}
              onSent={() => {
                void messagesResult.refetch();
                void settingsResult.refetch();
              }}
            />
          ) : null}
        </div>
      </div>
    </div>
  );
}
